language: python
python:
- '3.5.2'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y stockfish
install:
- pip install .
- pip install -r requirements.txt
before_script:
  - export PATH=$PATH:/usr/games/
script:
- python "./csa/test/test_csa.py"
